In [16]:
import tensorflow as tf
import keras
import config
import architecture
import numpy as np
from spektral.layers import GATConv

# Loading the model

In [10]:
model = keras.models.load_model("/home/buchalova/school/plASgraph2/experiments/with_normalization/1_h_lr_0.005_tie_True_norm_batch/model/saved_model.keras",
                             custom_objects={"plasgraph": architecture.plasgraph, "config": config.config})

Using attention layer


# Model summary

In [11]:
model.summary()

Model: "plasgraph"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (34310, 10)            │            70 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (34310, 32)            │           352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (34310, 32)            │           352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gat_conv_1 (GATConv)            │ ?                      │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (34310, 32)            │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (34310, 32)            │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (34310, 2)             │            66 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_27 (Dropout)            │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_28 (Dropout)            │ ?                      │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,218 (47.73 KB)

 Trainable params: 4,072 (15.91 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 8,146 (31.82 KB)

# Parameters of the layers

In [18]:
for i, layer in enumerate(model.layers):
    print(f"Layer index {i}: {layer.name}")
    print("Config:", layer.get_config())

Layer index 0: dense_6
Config: {'name': 'dense_6', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'units': 10, 'activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
Layer index 1: dense_7
Config: {'name': 'dense_7', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'units': 32, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'m

## 

In [21]:
for i, layer in enumerate(model._gnn_norm):
    print(i, layer.name)
    print(layer.get_config())

0 batch_normalization_6
{'name': 'batch_normalization_6', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'axis': -1, 'momentum': 0.99, 'epsilon': 0.001, 'center': True, 'scale': True, 'beta_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'gamma_initializer': {'module': 'keras.initializers', 'class_name': 'Ones', 'config': {}, 'registered_name': None}, 'moving_mean_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'moving_variance_initializer': {'module': 'keras.initializers', 'class_name': 'Ones', 'config': {}, 'registered_name': None}, 'beta_regularizer': None, 'gamma_regularizer': None, 'beta_constraint': None, 'gamma_constraint': None, 'synchronized': False}
1 batch_normalization_7
{'name': 'batch_normalization_7', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': '

## Normalization layer

# Weights of the model

In [24]:
for i, layer in enumerate(model.layers):
    print(f"Layer index {i}: {layer.name}")
    print("Weights:", model.layers[i].get_weights())

Layer index 0: dense_6
Weights: [array([[ 8.7201822e-01, -3.3427882e-01, -5.3308779e-01, -4.0941364e-01,
         4.8992801e-02, -1.9137226e-01,  1.3153374e-01,  4.8102507e-01,
        -1.4087833e-01, -8.5602576e-01],
       [-2.1112320e+00,  2.1662650e+00, -2.0587884e-01,  1.1990792e+00,
        -2.6500192e-01, -1.8732487e+00, -3.4394770e+00, -8.7195402e-01,
         5.0379906e+00,  3.5901792e+00],
       [ 8.2721859e-01, -5.7727031e-02, -1.1250057e+00, -1.8242626e-01,
         1.8657043e+00, -2.7275269e+00, -2.9445994e+00,  4.7247387e-03,
         2.2183151e+00, -2.0161514e-01],
       [ 4.7034803e-01,  3.6825222e-01,  4.7378525e-01, -7.0205343e-01,
        -9.7472298e-01,  5.6470168e-01, -4.0484205e-01,  2.3327872e-01,
         3.3310670e-01, -1.0600650e-01],
       [-6.7429322e-01,  6.5435541e-01,  1.1238852e+00, -8.1344128e-01,
        -7.9216218e-01,  9.1674954e-02, -2.1435294e+00, -1.9981439e-01,
         2.3459949e+00,  6.5237647e-01],
       [-1.8405703e-01, -1.7848752e-01,  7

# How attention and features change

In [30]:
X = tf.constant(
    [
        [0.1, 0.3, 0.2, 0.7, 0.0, 0.4],
        [0.2, 0.1, 0.5, 0.6, 0.1, 0.3],
        [0.9, 0.2, 0.1, 0.2, 0.3, 0.4],
        [0.8, 0.4, 0.2, 0.1, 0.5, 0.2],
    ],
    dtype=tf.float32,
)

A = tf.constant(
    [
        [1, 1, 0, 0],
        [1, 1, 1, 0],
        [0, 1, 1, 1],
        [0, 0, 1, 1],
    ],
    dtype=tf.float32,
)

In [38]:
x = model.preproc(X)
node_identity = model._fully_connected_input_1(x)
x = model._fully_connected_input_2(x)


old_gat = model._gnn_gcn[0]

new_gat = GATConv(
    channels=old_gat.channels,
    attn_heads=old_gat.attn_heads,
    concat_heads=old_gat.concat_heads,
    activation=old_gat.activation,
    use_bias=old_gat.use_bias,
    return_attn_coef=True,
)

mask_tensor = tf.ones((tf.shape(x)[0],), dtype=tf.float32)
_ = new_gat([x, A], mask=mask_tensor)

new_gat.set_weights(old_gat.get_weights())

out, attn = new_gat([x, A], mask=mask_tensor)

In [39]:
out # nove reprezentacie uzlov po GAT vrstve

<tf.Tensor: shape=(4, 32), dtype=float32, numpy=
array([[0.        , 0.37993538, 0.        , 0.02961162, 0.01427636,
        0.        , 0.        , 0.13963649, 0.        , 0.10943194,
        0.09941206, 0.08125695, 0.2273638 , 0.07514323, 0.02661788,
        0.19097432, 0.        , 0.        , 0.0749216 , 0.16747269,
        0.22630695, 0.        , 0.18402778, 0.15808454, 0.10910925,
        0.        , 0.        , 0.        , 0.06070757, 0.05922984,
        0.12044719, 0.        ],
       [0.        , 0.35911894, 0.        , 0.02921211, 0.01808104,
        0.        , 0.        , 0.13514972, 0.        , 0.10621086,
        0.09732053, 0.0819796 , 0.22007461, 0.07861827, 0.02373895,
        0.18910155, 0.        , 0.        , 0.07343867, 0.15991962,
        0.22170398, 0.        , 0.18108897, 0.15212017, 0.10848409,
        0.        , 0.        , 0.        , 0.06228912, 0.06183113,
        0.11257814, 0.        ],
       [0.        , 0.37091923, 0.        , 0.01964029, 0.01232525,
 

In [40]:
attn

<tf.Tensor: shape=(4, 1, 4), dtype=float32, numpy=
array([[[0.45870757, 0.5412924 , 0.        , 0.        ]],

       [[0.3049641 , 0.35986927, 0.33516666, 0.        ]],

       [[0.        , 0.36106175, 0.3362773 , 0.30266097]],

       [[0.        , 0.        , 0.5263064 , 0.4736936 ]]], dtype=float32)>